version: '3.8'

services:
  backend: 
    build: ./backend
    ports: 
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes: 
      - ./backend:/app
      - /app/node_modules 
    depends_on:
      - mongo

  frontend: 
    build: ./frontend
    ports:
      - "5173:5173"
    env_file: 
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"  
    volumes: 
      - mongo-data:/data/db    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data:
